language: elixir
elixir: 1.2.1
otp_release:
    - 18.0
services:
    - rabbitmq
    - redis-server
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - mkdir config
    - >
        echo '
        use Mix.Config

        config :amqp,
          host: "localhost",
          port: 5672,
          username: "guest",
          password: "guest",
          virtual_host: "/"

        config :exredis,
          host: "localhost",
          port: 6379,
          password: "",
          db: 1,
          reconnect: :no_reconnect,
          max_queue: :infinity

        config :postgrex, Yggdrasil.Repo,
          hostname: "localhost",
          username: "postgres",
          password: "postgres",
          database: "travis_ci_test"
        ' > config/config.exs
    - mix deps.get
script:
    - mix test
