language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.1
matrix:
    # We are only interested on the newest/oldest pair.
    exclude:
        - elixir: 1.4.0
          otp_release: 18.2
        - elixir: 1.3.2
          otp_release: 19.1
services:
  - rabbitmq
  - redis-server
  - postgresql
env:
  - TEST_YGGDRASIL_POSTGRES_DATABASE="travis_ci_test"
before_script:
  - psql -c "CREATE DATABASE '$TEST_YGGDRASIL_POSTGRES_DATABASE'" -U postgres
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
