language: elixir
elixir:
  - 1.3.4
  - 1.5.1
otp_release:
  - 18.3
  - 20.0
matrix:
    # We are only interested on the newest/oldest pair.
    exclude:
        - elixir: 1.5.1
          otp_release: 18.3
        - elixir: 1.3.4
          otp_release: 20.0
services:
  - rabbitmq
  - redis-server
  - postgresql
env:
  - TEST_YGGDRASIL_POSTGRES_DATABASE="travis_ci_test"
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/master/bin/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - sudo mkdir /usr/lib/rabbitmq/plugins
  - sudo wget https://bintray.com/rabbitmq/community-plugins/download_file\?file_path\=rabbitmq_delayed_message_exchange-0.0.1.ez -O /usr/lib/rabbitmq/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez
  - sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange
  - sudo ./rabbitmqadmin declare exchange name=custom.delayed_topic type=x-delayed-message durable=true 'arguments={"x-delayed-type":"topic"}'
  - psql -c "CREATE DATABASE $TEST_YGGDRASIL_POSTGRES_DATABASE" -U postgres
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
