language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.0
matrix:
    # We are only interested on the newest/oldest pair.
    exclude:
        - elixir: 1.4.0
          otp_release: 18.2
        - elixir: 1.3.2
          otp_release: 19.1
services:
  - rabbitmq
  - redis-server
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - >
      echo '
      use Mix.Config

      config :logger,
        level: :warn

      config :yggdrasil, Test,
        redis: [host: "localhost",
                port: 6379],
        rabbitmq: [host: "localhost",
                   port: 5672,
                   username: "guest",
                   password: "guest",
                   virtual_host: "/"],
        postgres: [hostname: "localhost",
                   username: "postgres",
                   password: "postgres",
                   database: "travis_ci_test"]
      ' > config/test.exs
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
